require('tsx/cjs');
const {test}=require('node:test'); const assert=require('node:assert/strict');const Module=require('node:module');
let cache=null,googleFails=false,eventFails=false,events=[],fetchCount=0;const original=Module._load;
Module._load=function(request,parent,main){
 if(request==='server-only')return {};
 if(request==='googleapis')return {google:{auth:{GoogleAuth:class{}},docs:()=>({documents:{get:async({documentId})=>{fetchCount++;if(googleFails)throw Error('simulated outage');return {data:{body:{content:[{paragraph:{elements:[{textRun:{content:documentId==='prompt'?'New instructions':'New reference'}}]}}]}}};}}})}};
 if(request==='@/lib/supabase/admin')return {createAdminClient:()=>({
  from:(name)=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:cache,error:null}),insert:async(value)=>{if(name==='advisor_events'){if(eventFails)return {error:{message:'simulated event outage'}};events.push(value)}return {error:null}}}),
  rpc:(name,args)=>({single:async()=>{if(name!=='write_advisor_document_cache')throw Error(name);if(!cache||new Date(cache.fetched_at)<new Date(args.p_fetch_started_at))cache={prompt_text:args.p_prompt_text,reference_text:args.p_reference_text,fetched_at:args.p_fetch_started_at};return {data:cache,error:null}}})
 })};
 return original.call(this,request,parent,main);
};
const {loadAdvisorDocuments}=require('../lib/server/google-docs.ts');const {generateAdvisorReply}=require('../lib/server/openrouter.ts');const {parseChatResponse,ChatRequestError,shouldDiscardPendingRequest}=require('../lib/chat-response.ts');const {estimateTokenBudget}=require('../lib/server/token-budget.ts');
const {loadAdvisorPrompt}=require('../lib/server/advisor-docs.ts');
const {titleFromMessage}=require('../lib/conversation-title.ts');
process.env.GOOGLE_DOC_CACHE_TTL_SECONDS='300';process.env.GOOGLE_PROMPT_DOC_ID='prompt';process.env.GOOGLE_REFERENCE_DOC_ID='reference';process.env.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64=Buffer.from(JSON.stringify({client_email:'isolated-test',private_key:'isolated-test'})).toString('base64');process.env.OPENROUTER_API_KEY='isolated-test';process.env.OPENROUTER_MODEL='openrouter/free';
const fresh=()=>({prompt_text:'Old instructions',reference_text:'Old reference',fetched_at:new Date().toISOString()});
test('fresh cache avoids Docs calls and records a hit',async()=>{cache=fresh();events=[];fetchCount=0;assert.equal((await loadAdvisorDocuments()).source,'cache');assert.equal(fetchCount,0);assert.equal(events[0].event_name,'prompt_cache_hit')});
test('an event insert outage does not prevent use of a valid cached prompt',async()=>{cache=fresh();events=[];eventFails=true;assert.equal((await loadAdvisorDocuments()).source,'cache');eventFails=false});
test('expired cache picks up edited documents without a restart',async()=>{cache={...fresh(),fetched_at:new Date(Date.now()-301000).toISOString()};events=[];const r=await loadAdvisorDocuments();assert.equal(r.source,'google');assert.equal(r.promptText,'New instructions');assert.equal(events[0].event_name,'prompt_cache_miss');assert.equal((await loadAdvisorDocuments()).source,'cache')});
test('parallel stale-cache requests share one Google Docs refresh in a process',async()=>{cache={...fresh(),fetched_at:new Date(0).toISOString()};fetchCount=0;const results=await Promise.all([loadAdvisorDocuments(),loadAdvisorDocuments(),loadAdvisorDocuments()]);assert.equal(fetchCount,2);assert.ok(results.every(result=>result.promptText==='New instructions'))});
test('Docs outage falls back to last good content with a durable diagnostic',async()=>{cache={...fresh(),fetched_at:new Date(0).toISOString()};googleFails=true;events=[];assert.equal((await loadAdvisorDocuments()).source,'stale-cache');assert.equal(events[1].event_name,'doc_fetch_error');assert.equal(events[1].metadata.fallback,true)});
test('Docs outage without cache fails closed',async()=>{cache=null;events=[];await assert.rejects(loadAdvisorDocuments(),e=>e.status===503);assert.equal(events[1].metadata.fallback,false);googleFails=false});
test('the full short reference is included without keyword selection',async()=>{cache={...fresh(),reference_text:'First principle: pause before buying.\nSecond principle: check recurring costs.'};events=[];const result=await loadAdvisorPrompt();assert.equal(result.documentSource,'cache');assert.ok(result.systemPrompt.includes(cache.reference_text));assert.ok(result.systemPrompt.includes(cache.prompt_text));assert.equal(events[0].event_name,'prompt_cache_hit')});
test('provider throttle sends usable retry guidance and safe event data',async()=>{events=[];global.fetch=async()=>new Response('{}',{status:429});await assert.rejects(generateAdvisorReply([{role:'user',content:'private input'}]),e=>e.status===429&&e.retryAfterSeconds===60);assert.deepEqual(events[0].metadata,{kind:'http',status:429});assert.ok(!JSON.stringify(events).includes('private input'))});
test('provider network and malformed output errors are recorded',async()=>{events=[];global.fetch=async()=>{throw Error('simulated timeout')};await assert.rejects(generateAdvisorReply([]),e=>e.status===502&&e.code==='provider_unavailable');global.fetch=async()=>new Response('not json');await assert.rejects(generateAdvisorReply([]),e=>e.status===502&&e.code==='invalid_response');assert.deepEqual(events.map(e=>e.metadata.kind),['connection','invalid_response'])});
test('safety-only model output is rejected and a prefixed answer is cleaned',async()=>{for(const label of ['User Safety','Response Safety']){events=[];global.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:`${label}: safe.`}}]}));await assert.rejects(generateAdvisorReply([]),e=>e.status===502);assert.equal(events.at(-1).metadata.kind,'invalid_response');global.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:`${label}: safe\n\nWhat purchase are you considering?`}}]}));assert.equal((await generateAdvisorReply([])).reply,'What purchase are you considering?')}});
test('stacked safety labels are removed from the visible reply',async()=>{global.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:'User Safety: safe\nResponse Safety: safe\n\nHello!'}}]}));assert.equal((await generateAdvisorReply([])).reply,'Hello!')});
test('automatic chat titles preserve complete emoji graphemes at the boundary',()=>{const title=titleFromMessage('a'.repeat(59)+'😀 should I buy this?');assert.equal(title,'a'.repeat(59));assert.equal(titleFromMessage('😀 should I buy this?'),'😀 should I buy this?')});
test('retry parser honors header and JSON delay, avoids daily-cap countdown',async()=>{await assert.rejects(parseChatResponse(new Response(JSON.stringify({error:'Wait',retryAfterSeconds:9}),{status:429,headers:{'Retry-After':'13'}})),e=>e.retryAfterSeconds===13);await assert.rejects(parseChatResponse(new Response(JSON.stringify({error:'Wait',retryAfterSeconds:9}),{status:429})),e=>e.retryAfterSeconds===9);await assert.rejects(parseChatResponse(new Response(JSON.stringify({error:'Daily cap',code:'token_cap'}),{status:429})),e=>e.retryAfterSeconds===0)});
test('known failed turns allow a fresh manual attempt but ambiguous requests retain their ID',()=>{for(const code of ['previous_failed','previous_uncertain','provider_unavailable','invalid_response'])assert.equal(shouldDiscardPendingRequest(new ChatRequestError('failed',502,code)),true);for(const code of ['processing','conversation_busy'])assert.equal(shouldDiscardPendingRequest(new ChatRequestError('wait',409,code)),false);assert.equal(shouldDiscardPendingRequest(new ChatRequestError('unknown',500)),false)});
test('reservation includes Unicode bytes, full history and response allowance',()=>{const a=estimateTokenBudget([{role:'user',content:'a'}]);assert.ok(a>=500);assert.equal(estimateTokenBudget([{role:'user',content:'你好'}])-a,5);assert.ok(estimateTokenBudget([{role:'user',content:'a'},{role:'assistant',content:'history'}])>a)});
